### ISSUE TITLE
'networkgrp' attribute and everywhere to everywhere routes

### ISSUE THREAD

**Issue by rruiz-s** [reirby/PostGisRoadNetworkAnalysis#1]
Good morning,

First of all, thank you very much for publishing your analysis and code. It is exactly what I was looking for. Just two questions.

In your code, in the line 25 within the section 'marks segments for merging', you mentioned the attribute 'networkgrp. 
*1. Where can I find information about that column?*

My data, derived from Open Street Map, looks like:

| gid | source | target | cost | unidirectid | bidirectid | the_geom |
| ---|--- | ---|---|---|---|---|
| 1 | 861 | 0 | 4.25284 | 1 | 1 | LINESTRING(-51.87875 -29.162416, -51.878847 -29.162481)|

I used bidirectid instead of networkgrp, so I could keep running the code, which brings me to the second question.

*2. Is it possible that in the section 'Calculate new table of everywhere to everywhere routes using dijkstra many to many' could crash the machine if the network is too large?*.

In my case, everything went smoothly till that point, when the computer got frozen.
For context,  the table with the vertices includes 5137 vertices and 12486 edges.

Thank  you very much again for sharing your work!

**Comment by reirby** [comment]
Hello Ricardo, you a very welcome! I am glad that you found this useful.

1) The 'networkgrp' column comes from the[ Disconnected Islands ](https://plugins.qgis.org/plugins/disconnected-islands/) Qgis plugin. It checks whether your network is a single piece, or there are some disconnected areas.

2) Yes, it is  possible. If I remember well, it mostly depends on the amount of available memory.

Hope that helps.

Best,
Andrei

**Comment by rruiz-s** [comment]
Hello Andre

Thank you so much for your explanation and quick response!

It is clear now why merging the segments that belong to the same single piece or component/self-connected network.
